### ISSUE TITLE
Travis failing on Perl 5.12 and 5.19

### ISSUE THREAD

**Issue by michal-josef-spacek** [nichtich/Catmandu-Wikidata#11]
Travis failing on Perl 5.12 and 5.19, so we need fix it.

I am proposing to remove 5.19 (development version).
And i removed 5.12 in my releases too. But i don't precisely don't understand this versions in travis.
I am proposing to add other stable versions > 5.18.

**Comment by nichtich** [comment]
Better replace Travis with [GitHub workflows](https://github.com/nichtich/Catmandu-Wikidata/actions), I'm trying to do so.

**Comment by nichtich** [comment]
I changed minimum requirement to Perl 5.14 and replaced Travis by GitHub workflow.
