### ISSUE TITLE
Examples from synopsis don't work

### ISSUE THREAD

**Issue by jorol** [nichtich/Catmandu-Wikidata#12]
Examples form synopsis 

```
catmandu convert Wikidata --ids Q1,P227
catmandu convert Wikidata --site dewiki --title Wahnsinn
```

don't get any data... I guess it's a problem with Catmandu::Importer::getJSON, see https://github.com/nichtich/Catmandu-Importer-getJSON/issues/24.

**Comment by michal-josef-spacek** [comment]
@jorol This commands are working for me. I installed fresh Catmandu::Wikidata and test and it's working.
What's your result?

**Comment by jorol** [comment]
@michal-josef-spacek Thanks for your comment. Just tested it on another machine, works fine... Perhaps it is problem with the proxy server at my workplace.
